POST http://localhost:3000/api/post/
Content-Type: application/json

{
    "number": 11,
    "available": true
}
###
GET http://localhost:3000/api/getAll/

###
GET http://localhost:3000/api/users/
###

GET http://localhost:3000/api/getOne/639b361aff0b7f81809cfaa5
###
PATCH http://localhost:3000/api/update/639b361aff0b7f81809cfaa5
Content-Type: application/json

{
    "available": true
}
###

POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "firstName": "test1",
    "lastName": "lastname",
    "email": "test@yahoo.com",
    "username": "nas2",
    "password": "12345"
}
###

GET http://localhost:3000/api/appointments/2022-12-24
###

POST http://localhost:3000/api/users/gs
Content-Type: application/json

{
    "password": "password"
}
###
GET http://localhost:3000/api/appointments/

###
PATCH  http://localhost:3000/api/appointments/63a4232f9d1e6e72c48419e9
Content-Type: application/json

{
    "username": "nb",
    "available": 0
}