POST http://localhost:3000/api/post/
Content-Type: application/json

{
    "number": 11,
    "available": true
}
###
GET http://localhost:3000/api/getAll/
###
GET http://localhost:3000/api/appointments/
###
GET http://localhost:3000/api/users/
###

GET http://localhost:3000/api/getOne/639b361aff0b7f81809cfaa5
###
PATCH http://localhost:3000/api/update/639b361aff0b7f81809cfaa5
Content-Type: application/json

{
    "available": true
}
###